version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: chooselife_postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chooselife
      POSTGRES_HOST: postgres
      DATABASE_PORT: 5432
      POSTGRES_HOSTNAME: 127.0.0.1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: chooselife_redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  postgres-data:
  pgadmin-data:
  redis: