export const startDate = new Date("2025-06-19");
export const endDate = new Date("2025-06-22");
export const highlinesID = [
  "162394aa-0653-4b6f-b78a-612bb2697a03",
  "636b62f3-872f-4e18-9df2-3e9645606d62",
];

export type TScheduleData = {
  id: number;
  title: string;
  instructor?: string;
  startAt: string;
  type?: "workshop" | "competition";
  location?: string;
  day?: string;
};

export const scheduleData: TScheduleData[] = [
  // Quinta-feira: 2025-06-19
  {
    id: 1,
    title: "Yoga e Respiração",
    instructor: "Micaela Franzel",
    startAt: "08:00 - 09:00",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-19",
  },
  {
    id: 2,
    title: "Altinha",
    startAt: "09:30 - 10:30",
    type: "workshop",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-19",
  },
  {
    id: 3,
    title: "LACAM - oficina de produtos canábicos",
    instructor: "Alisson Gabriel",
    startAt: "11:00 - 12:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-19",
  },
  {
    id: 4,
    title: "Espaço Cuidado - Acupuntura, Auriculoterapia, Ventosaterapia",
    instructor: "Nathalia Tavares",
    startAt: "13:00 - 16:00",
    type: "workshop",
    location: "🌿 Espaço Cuidado (Oficinas)",
    day: "2025-06-19",
  },
  {
    id: 5,
    title: "Roda de Conversa - Ouvidoria Delas",
    startAt: "16:30 - 17:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-19",
  },
  {
    id: 6,
    title: "Oficina de capoeira + Roda de Capoeira",
    instructor: "Angoleiros do Sertão",
    startAt: "18:00 - 20:00",
    type: "workshop",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-19",
  },
  {
    id: 7,
    title: "Montagem Banda de Reggae",
    startAt: "20:00 - 21:00",
    location: "🎤 Palco",
    day: "2025-06-19",
  },
  {
    id: 8,
    title: "Show de Reggae",
    startAt: "21:00 - 23:00",
    location: "🎤 Palco",
    day: "2025-06-19",
  },
  {
    id: 9,
    title: "DJ",
    startAt: "23:00",
    location: "🎤 Palco",
    day: "2025-06-19",
  },

  // Sexta-feira: 2025-06-20
  {
    id: 10,
    title: "Yoga",
    instructor: "Alice Amaral",
    startAt: "08:00 - 09:00",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-20",
  },
  {
    id: 11,
    title: "Pratique Movimento",
    startAt: "09:30 - 10:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-20",
  },
  {
    id: 12,
    title: "Corpos em Diálogo - Pontos de (des)equilibrio em duo",
    instructor: "Camila Ferreira",
    startAt: "11:00 - 12:00",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-20",
  },
  {
    id: 13,
    title: "Oficina de Tecer Mandalas em linhas",
    instructor: "Felipe Braga",
    startAt: "14:00 - 15:00",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-20",
  },
  {
    id: 14,
    title: "Massagem e Yoga",
    instructor: "Laís Cacciari",
    startAt: "15:30 - 17:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-20",
  },
  {
    id: 15,
    title: "Forró nas Alturas",
    instructor: "João Manoel da Silva Parreira",
    startAt: "18:00 - 19:30",
    location: "🎤 Palco",
    day: "2025-06-20",
  },
  {
    id: 16,
    title: "Oficina de Forró",
    instructor: "André Kenzo e Beatriz Furtado",
    startAt: "20:00 - 21:00",
    type: "workshop",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-20",
  },
  {
    id: 17,
    title: "Forró",
    startAt: "21:00",
    location: "🎤 Palco",
    day: "2025-06-20",
  },

  // Sábado: 2025-06-21
  {
    id: 18,
    title: "Yoga",
    instructor: "Bianca Machado + Lotus",
    startAt: "08:00 - 09:00",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-21",
  },
  {
    id: 19,
    title: "Elaboración de sahumerios artesanais - Aula de YOGA",
    instructor: "Verónica Daniela",
    startAt: "09:30 - 10:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-21",
  },
  {
    id: 20,
    title: "Crossfit Selva",
    instructor: "Wendy lee e Ruggeri",
    startAt: "11:00 - 12:00",
    type: "workshop",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-21",
  },
  {
    id: 21,
    title: "Yoga",
    instructor: "Mariana Sarmento",
    startAt: "12:30 - 13:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-21",
  },
  {
    id: 22,
    title: "Yoga - Kemetic",
    instructor: "Ismael Afonso",
    startAt: "15:00 - 16:00",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-21",
  },
  {
    id: 23,
    title: "Oficina de Perna de Pau",
    instructor: "Giulia Largares",
    startAt: "16:30 - 17:30",
    type: "workshop",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-21",
  },
  {
    id: 24,
    title: "Oficina de Bambolê",
    instructor: "Voarte",
    startAt: "18:00 - 19:00",
    type: "workshop",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-21",
  },
  {
    id: 25,
    title: "Alongamento Dinâmico",
    instructor: "Ana Luisa Amaral",
    startAt: "19:30 - 20:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-21",
  },
  {
    id: 26,
    title: "Cerimônia de premiação das modalidades e Rifa",
    startAt: "21:00 - 23:00",
    location: "🎤 Palco",
    day: "2025-06-21",
  },
  {
    id: 27,
    title: "Batalha de Rima",
    startAt: "23:00 - 00:00",
    type: "competition",
    location: "🎤 Palco",
    day: "2025-06-21",
  },
  {
    id: 28,
    title: "BAILE DO CHOOSE + performance coletivo YABAS (fogo)",
    instructor: "Ana Luisa Amaral (performance YABAS)",
    startAt: "00:00",
    location: "🎤 Palco",
    day: "2025-06-21",
  },

  // Domingo: 2025-06-22
  {
    id: 29,
    title: "Yoga - Ashtanga Vinyasa e Parada de Mão",
    instructor: "Luciana Casares Yoga 2",
    startAt: "08:00 - 09:00",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-22",
  },
  {
    id: 30,
    title: "Soundhealing",
    instructor: "Lotus Branca e Sara",
    startAt: "09:30 - 10:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-22",
  },
  {
    id: 31,
    title: "Oficina de Jiu Jitsu e noções de defesa pessoal",
    instructor: "Gabriel Schardong",
    startAt: "11:00 - 12:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-22",
  },
  {
    id: 32,
    title: "Acrobacia em dupla/grupo",
    instructor: "Matheus Kamla",
    startAt: "14:00 - 15:00",
    type: "workshop",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-22",
  },
  {
    id: 33,
    title: "Yoga + Sound healing",
    instructor: "Bianca + Lotus branca e Sara",
    startAt: "15:30 - 16:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-22",
  },
  {
    id: 34,
    title: "Oficina de Massagem e Automassagem",
    instructor: "Ariadne",
    startAt: "17:00 - 18:30",
    type: "workshop",
    location: "🛠️ Espaço Oficinas",
    day: "2025-06-22",
  },
  {
    id: 35,
    title: "Cinema de Bolso",
    instructor: "Maria Flávia Borgonovi Pachá",
    startAt: "19:00 - 21:00",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-22",
  },
  {
    id: 36,
    title: "Sessão de Cinema",
    startAt: "21:00 - 00:00",
    location: "🛠️🎤 Espaço Oficinas / Palco",
    day: "2025-06-22",
  },
];
