name: Check Translations Format

on:
  pull_request:

jobs:
  check-translations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.11.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run format:translations check
        run: yarn format:translations
